version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flowtrace_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flowtrace-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - flowtrace-network

  backend:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile.dev
    command: bash -c "bundle exec rails db:create; bundle exec rails db:migrate; bundle exec rails db:seed; bundle exec rails server -b 0.0.0.0 -p 5609"
    volumes:
      - bundle_cache:/usr/local/bundle
    ports:
      - "5609:5609"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/flowtrace_development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
      - SECRET_KEY_BASE=development_secret_key_base_replace_in_production
      - RAILS_LOG_LEVEL=debug
      - PORT=5609
    networks:
      - flowtrace-network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile.dev
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0 --port 5601"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5601:5601"
      - "5602:5602"  # HMR port
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:5609
    networks:
      - flowtrace-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
  node_modules:

networks:
  flowtrace-network:
    driver: bridge
