version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flowtrace_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flowtrace-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - flowtrace-network

  web:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/flowtrace_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    networks:
      - flowtrace-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - flowtrace-network

volumes:
  postgres_data:
  bundle_cache:
  node_modules:

networks:
  flowtrace-network:
    driver: bridge
